site_name: isitfit
repo_url: https://github.com/autofitcloud/isitfit/
edit_uri: ""

nav:
  - Home: index.md
  - Concepts: concepts.md
  - Installation: installation.md
  - Usage: usage.md
  - Synopsis: synopsis.md
  - Statistics: statistics.md
  - AutofitCloud: https://www.autofitcloud.com

extra_css:
  - css/extra.css
copyright: Copyright &copy; 2019 <a href="https://www.autofitcloud.com">AutofitCloud</a>.
plugins: []
